#!/usr/bin/env bash
set -e
TARGET=${TARGET:-}

usage() {
    EXAMPLES=$(examples 2>&1)
    cat << EOT >&2
Show debug information about thin-edge.io by connecting to the device via ssh.

Information is gather about the device and can be used when uploading to a Github
ticket on https://github.com/thin-edge/thin-edge.io/issues/new?assignees=&labels=bug&projects=&template=bug_report.md

USAGE
  c8y tedge debug show <TARGET>

ARGUMENTS
  TARGET              Device hostname or ip to connect to via ssh. E.g. root@mydevice.local

FLAGS
  --examples          Show examples only
  -h, --help          Show this help

$EXAMPLES

EOT
}

examples() {
    cat << EOT >&2
EXAMPLES

# Print debug information about the thin-edge.io device
c8y tedge debug show root@mydevice.local

# (MacOS only) Print debug info but copy the markdown directly to the copy/paste buffer
c8y tedge debug show root@rpi5-d83add9f145a.local | pbcopy

EOT
}

#
# Parse args
#
while [ $# -gt 0 ]; do
    case "$1" in
        --examples)
            examples
            exit 0
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            if [ -z "$TARGET" ]; then
                TARGET="$1"
            elif [ -z "$DEVICE_ID" ]; then
                DEVICE_ID="$1"
            fi
    esac
    shift
done

if [ -z "$TARGET" ]; then
    echo "Missing required positional arugment. TARGET" >&2
    usage
    exit 1
fi

MODEL=$(ssh "$TARGET" cat /proc/cpuinfo | grep Model | cut -d: -f2- | xargs)
OS_NAME=$(ssh "$TARGET" cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2- | tr -d \")
UNAME=$(ssh "$TARGET" uname -a)
TEDGE_VERSION=$(ssh "$TARGET" tedge --version)

# Note: Print instructions on stderr, but print actual output to stdout
# so that it can be copied/pasted easier, e.g. using piping `pbcopy`

printf '\n' >&2
printf 'Debug information: (copy/paste to the ticket)\n\n' >&2
printf '  https://github.com/thin-edge/thin-edge.io/issues/new?assignees=&labels=bug&projects=&template=bug_report.md\n' >&2
printf '\n' >&2
printf '|Property|Value|\n'
printf '|--------|-----|\n'
printf '|OS [incl. version]|`%s`|\n' "${OS_NAME:-unknown}"
printf '|Hardware [incl. revision]|`%s`|\n' "${MODEL:-unknown}"
printf '|System-Architecture|`%s`|\n' "$UNAME"
printf '|thin-edge.io version|`%s`|\n' "$TEDGE_VERSION"
printf '' >&2
