#!/usr/bin/env bash
set -e
TARGET=${TARGET:-}
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
LEVEL=1

usage() {
    EXAMPLES=$(examples 2>&1)
    cat << EOT >&2
Show debug information about thin-edge.io by connecting to the device via ssh.

Information is gather about the device and can be used when uploading to a Github
ticket on https://github.com/thin-edge/thin-edge.io/issues/new?assignees=&labels=bug&projects=&template=bug_report.md

USAGE
  c8y tedge debug show <TARGET>

ARGUMENTS
  TARGET              Device hostname or ip to connect to via ssh. E.g. root@mydevice.local

FLAGS
  --examples          Show examples only
  -h, --help          Show this help

$EXAMPLES

EOT
}

examples() {
    cat << EOT >&2
EXAMPLES

# Print debug information about the thin-edge.io device
c8y tedge debug show root@mydevice.local

# (MacOS only) Print debug info but copy the markdown directly to the copy/paste buffer
c8y tedge debug show root@rpi5-d83add9f145a.local | pbcopy

EOT
}

#
# Parse args
#
while [ $# -gt 0 ]; do
    case "$1" in
        --level)
            LEVEL="$2"
            shift
            ;;
        --examples)
            examples
            exit 0
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            if [ -z "$TARGET" ]; then
                TARGET="$1"
            elif [ -z "$DEVICE_ID" ]; then
                DEVICE_ID="$1"
            fi
    esac
    shift
done

if [ -z "$TARGET" ]; then
    echo "Missing required positional arugment. TARGET" >&2
    usage
    exit 1
fi

# copy script to remote device
scp "$SCRIPT_DIR/../../data/tedge-debug.sh"  "${TARGET}:/tmp/" >&2
ssh "$TARGET" chmod +x /tmp/tedge-debug.sh >&2
ssh "$TARGET" /tmp/tedge-debug.sh --level "$LEVEL" >&2

DEBUG_FILE="./${TARGET}-debug.tar.gz" >&2
scp "${TARGET}:/tmp/debug.tar.gz" "$DEBUG_FILE" >&2


tar xvzf "$DEBUG_FILE" ./device.txt >&2
source ./device.txt

# Note: Print instructions on stderr, but print actual output to stdout
# so that it can be copied/pasted easier, e.g. using piping `pbcopy`

printf '\n' >&2
printf 'Debug information: (copy/paste to the ticket)\n\n' >&2
printf '  https://github.com/thin-edge/thin-edge.io/issues/new?assignees=&labels=bug&projects=&template=bug_report.md\n' >&2
printf '\n' >&2


cat << EOT
**Describe the bug**
<!-- A clear and concise description of what the bug is.  -->

**To Reproduce**
<!-- Steps to reproduce the behavior. The more detail you add here, the better we can reproduce the bug. -->

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment (please complete the following information):**

|Property|Value|
|--------|-----|
|OS [incl. version]|\`$OS_NAME\`|
|Hardware [incl. revision]|\`$MODEL\`|
|System-Architecture|\`$UNAME\`|
|thin-edge.io version|\`$TEDGE_VERSION\`|
|mosquitto version|\`$MOSQUITTO_VERSION\`|

**Additional context**
<!-- Add any other context about the problem here. -->

EOT


printf '\n\nUpload the following file to the ticket:\n' >&2
printf '\n' >&2
printf '    %s' "$DEBUG_FILE"  >&2
printf '\n' >&2


# TODO create ticket via gh command
# gh issue create
