#!/bin/sh
set -e

if [ "${DEBUG:-}" = 1 ]; then
    set -x
fi

usage() {
    cat <<EOT >&2
List the existing tedge-container-bundle instances

c8y tedge container-bundle list

Examples

  c8y tedge container-bundle list
  # List all existing instances

EOT
}

while [ $# -gt 0 ]; do
    case "$1" in
        --help|-h)
            usage
            exit 0
            ;;
        *)
            break
            ;;
    esac
done

# Try auto detecting container cli (based on what is available)
if [ -z "$C8Y_TEDGE_CONTAINER_CLI" ]; then
    if command -V docker >/dev/null 2>&1; then
        C8Y_TEDGE_CONTAINER_CLI=docker
    elif command -V nerdctl >/dev/null 2>&1; then
        C8Y_TEDGE_CONTAINER_CLI=nerdctl
    elif command -V podman >/dev/null 2>&1; then
        C8Y_TEDGE_CONTAINER_CLI=podman
    fi
fi

if [ -z "$C8Y_TEDGE_CONTAINER_CLI" ]; then
    echo "Error: Could not find a container cli, e.g. docker, nerdctl, podman" >&2
    exit 1
fi

echo "Using container cli: $C8Y_TEDGE_CONTAINER_CLI" >&2

echo "Existing tedge-container-bundle instances (label=c8y.tedge.container.bundle=1)" >&2

# jsonnet template to extract container info including the c8y.url which is stored in the label
JSONNET_TEMPLATE='
{
  State: input.value.State,
  Name: std.strReplace(input.value.Names, "/", ""),
  url: std.join("," , [
      std.splitLimit(x,"=",1)[1]
      for x in std.split(input.value.Labels,",")
      if std.startsWith(x, "c8y.url=")
    ]
  ),
}
'
CONTAINER_NAMES=$(
    $C8Y_TEDGE_CONTAINER_CLI container list -a --filter "label=c8y.tedge.container.bundle=1" --format='{{. | json}}' \
    | c8y template execute --template "$JSONNET_TEMPLATE" --output csv --select "Name,State,url"
)

if [ -z "$CONTAINER_NAMES" ]; then
    echo "No tedge-container-bundles instances exist" >&2
    exit 0
fi

# loop through the demo container and print using go-c8y-cli formatting
(
    for CONTAINER_INFO in $CONTAINER_NAMES; do

        NAME=$(echo "$CONTAINER_INFO" | cut -d, -f1)
        STATE=$(echo "$CONTAINER_INFO" | cut -d, -f2)
        URL_FROM_LABEL=$(echo "$CONTAINER_INFO" | cut -d, -f3)

        # get tedge config
        CONFIG=$("$C8Y_TEDGE_CONTAINER_CLI" exec "$NAME" tedge config list 2>/dev/null ||:)
        URL=$(echo "$CONFIG" | grep c8y.http | head -n1 | cut -d= -f2 | cut -d: -f1)
        if [ -z "$URL" ]; then
            URL=$(echo "$CONFIG" | grep c8y.url | head -n1 | cut -d= -f2 | cut -d: -f1)
        fi
        if [ -z "$URL" ] && [ -n "$URL_FROM_LABEL" ]; then
            URL="$URL_FROM_LABEL"
        fi
        if [ -n "$URL" ]; then
            URL="https://$URL"
        fi

        # get tedge version
        TEDGE_VERSION=$("$C8Y_TEDGE_CONTAINER_CLI" exec "$NAME" tedge --version 2>/dev/null | cut -d' ' -f2- ||:)

        printf '{"name":"%s","state":"%s","url":"%s","tedgeVersion":"%s"}\n' "$NAME" "${STATE:-"-"}" "${URL:-"-"}" "${TEDGE_VERSION:-"-"}"
    done
) | C8Y_SETTINGS_VIEWS_COLUMNPADDING=20 c8y util show --select name,state,tedgeVersion,url

