#!/bin/sh
set -e

if [ "${DEBUG:-}" = 1 ]; then
    set -x
fi

usage() {
    cat <<EOT >&2
List the existing tedge-container-demo instances

c8y tedge demo list

Examples

  c8y tedge demo list
  # List all existing demos

EOT
}

while [ $# -gt 0 ]; do
    case "$1" in
        --help|-h)
            usage
            exit 0
            ;;
        *)
            break
            ;;
    esac
done

PROJECT_DIR="$HOME/.tedge/tedge-demo-container/$NAME"
export COMPOSE_FILE="$PROJECT_DIR/docker-compose.yaml"

echo "Existing demos under: $PROJECT_DIR" >&2

ls -c1 "$PROJECT_DIR"
