#!/bin/sh
set -e

FEATURES="${FEATURES:-}"

if [ "${DEBUG:-}" = 1 ]; then
    set -x
fi

usage() {
    cat <<EOT >&2
Start a new tedge-demo-container instance

It will download the latest docker-compose from the https://github.com/thin-edge/tedge-demo-container repository
and bootstrap it using your current go-c8y-cli session.

c8y tedge demo start [DEVICE_NAME] [--features <pki|nopki>]

Arguments

  --features <feature_set>      List of features to activate. e.g. nopki

Examples

  c8y tedge demo start
  # Start a tedge-demo-container using a randomly generated device name

  c8y tedge demo start mydevice001
  # Start a tedge-demo-container using the device name 'mydevice001'

  c8y tedge demo start mydevice001 --features nopki
  # Start a tedge-demo-container but disable the usage of the local PKI

EOT
}

fail() {
    echo "ERROR: $*" >&2
    exit 1
}

POSITIONAL_ARGS=

while [ $# -gt 0 ]; do
    case "$1" in
        --features)
            FEATURES="$2"
            shift
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            POSITIONAL_ARGS=" $POSITIONAL_ARGS"
            ;;
    esac
    shift
done

# shellcheck disable=SC2086
set -- $POSITIONAL_ARGS

if [ $# -gt 0 ]; then
    NAME="$1"
    shift
else
    NAME=$(c8y template execute --template "'tedge_' + _.Hex(8)")
    echo "Using randomly generated device name: $NAME" >&2
fi

COMPOSE_URL="https://raw.githubusercontent.com/thin-edge/tedge-demo-container/main/demos/docker-compose/device/docker-compose.yaml"
PROJECT_DIR="$HOME/.tedge/tedge-demo-container/$NAME"
export COMPOSE_FILE="$PROJECT_DIR/docker-compose.yaml"

echo "Creating demo folder: $PROJECT_DIR" >&2
mkdir -p "$PROJECT_DIR"

echo "Downloading the docker-compose.yaml file" >&2
if command -V wget >/dev/null 2>&1; then
    wget -q -O - "$COMPOSE_URL" > "$COMPOSE_FILE"
elif command -V curl >/dev/null 2>&1; then
    curl -LSs "$COMPOSE_URL" > "$COMPOSE_FILE"
else
    fail "Missing required dependencies: Either curl or wget is needed"
fi

if [ -n "$FEATURES" ]; then
    echo "Setting non-default features: FEATURES=$FEATURES" >&2
    echo "FEATURES='$FEATURES'" > "$PROJECT_DIR/.env"
fi

echo "Running docker compose up -d" >&2
(cd "$PROJECT_DIR" && docker compose up -d)

echo "Bootstrapping" >&2
c8y tedge bootstrap-container tedge --device-id "$NAME" "$@"

# Create a default remoteaccess configuration but only if the user has the correct permissions
MO_ID=$(c8y identity get -n --name "$NAME" --select managedObject.id -o csv)
if [ -n "$MO_ID" ]; then
    # Check if the user had correct permissions to use remoteaccess
    if c8y remoteaccess configurations list -n --device "$MO_ID" --silentStatusCodes 403; then
        # Add webssh config if it is not already existing
        c8y remoteaccess configurations get -n --id webssh --device "$MO_ID" --silentStatusCodes 404 ||
            c8y remoteaccess configurations create-webssh \
                -n \
                --device "$MO_ID" \
                --name "webssh" \
                --credentialsType USER_PASS \
                --username iotadmin \
                --password iotadmin \
                --force >/dev/null
    else
        echo "Warning: We couldn't add the remote access configuration as you don't have the required permissions"
        echo "To fix this: Add the 'Remote Access' permission to a role like 'Admin' and assign yourself to it"
    fi
fi
