#!/bin/sh
set -e

KEEP_DEVICE="${KEEP_DEVICE:-0}"

if [ "${DEBUG:-}" = 1 ]; then
    set -x
fi

usage() {
    cat <<EOT >&2
Stop an existing tedge-container-demo instance

c8y tedge demo stop <DEVICE_NAME> [--keep]

Arguments
  --keep        Don't delete the device and device user in Cumulocity

Examples

  c8y tedge demo stop mydevice001
  # Stop an demo instance with the device name 'mydevice001'

  c8y tedge demo stop mydevice001 --keep
  # Stop an demo instance with the device name 'mydevice001'

EOT
}

fail() {
    echo "ERROR: $*" >&2
    exit 1
}

POSITIONAL_ARGS=""

while [ $# -gt 0 ]; do
    case "$1" in
        --keep)
            KEEP_DEVICE=1
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            POSITIONAL_ARGS="$POSITIONAL_ARGS $1"
            ;;
    esac
    shift
done

# shellcheck disable=SC2086
set -- $POSITIONAL_ARGS

if [ $# -lt 1 ]; then
    fail "Missing device name (aka project name)"
fi
NAME="$1"
shift

PROJECT_DIR="$HOME/.tedge/tedge-demo-container/$NAME"
export COMPOSE_FILE="$PROJECT_DIR/docker-compose.yaml"

if [ ! -f "$COMPOSE_FILE" ]; then
    echo "Demo does not exist (under $PROJECT_DIR)" >&2
    exit 0
fi

(cd "$PROJECT_DIR" && docker compose down -v)
rm -rf "$PROJECT_DIR"

# Delete the device from Cumulocity
if [ "$KEEP_DEVICE" != 1 ]; then
    echo "Removing device and related device user. externalId=$NAME" >&2
    c8y identity get -n --name "$NAME" | c8y devices delete --cascade --force >/dev/null ||:
    c8y users delete --id "device_$NAME" --force >/dev/null ||:
fi
